In [58]:
from gensim.models import FastText
from konlpy.tag import Twitter

In [56]:
import pandas as pd

In [57]:
with open("../code/data/small/train/train_data") as f:
    data = f.readlines()
    data = [str(t.strip()) for t in data]
    data = pd.DataFrame(data, columns=['comment'])
    
with open("../code/data/small/train/train_label") as f:
    score = f.readlines()
    data['score'] = pd.DataFrame(score)
    data['score'] = data['score'].map(lambda x: int(x.strip()))

In [60]:
tokenizer = Twitter()

In [61]:
reviews = data['comment'].values

In [62]:
tokenized_reviews = [tokenizer.pos(review, stem=False) for review in reviews]

In [64]:
tokens = [[token for token, pos in tokenized_list] for tokenized_list in tokenized_reviews]
tags = [[pos for token, pos in tokenized_list] for tokenized_list in tokenized_reviews]

In [82]:
tokens

['아련한', '향수', '를', '떠올리', '게', '만드는', '추억', '의', '영화']

In [109]:
fasttext = FastText(sentences=tokens,
                         sg=1,
                         window=5,
                         negative=10,
                         min_n=2,
                         max_n=5,
                         word_ngrams=1,
                         size=300,
                         iter=20,
                         sorted_vocab=1,
                         )

In [110]:
fasttext.

dict_keys(['아련한', '향수', '를', '떠올리', '게', '만드는', '추억', '의', '영화', 'SF', '코미디', '영화사', '에서', '가장', '해', '야할', 'mv', '00036133', '꿈', '이', '란', '히', '진', '최고', '전편', '을', '%', '천재', '적', '인', '속편', '.', '1', '편', '만큼', '재미있다', '3', '만', '조금', '역시', '능가', '하는', '은', '다', '무슨', '설명', '더', '필요한', '가', '?', '00501003', '라는', '이름', '만으로도', '힘', '때', '참', 'ac', '00000559', '멋져', '지', '면서도', '심장', '온', '00457204', '에', '계속', '도', '보게', '캐빈', '이면', '항상', '먼저', '가족영화', "'", '와', '함께', '언제', '고', '케빈', 'T', '같은', '친구', '한', '명', '있었', '으면', '...', '영원한', '스칼렛', '으로', '기억', '될', '록키', '시리즈', '통틀어', '!!!!', '전개', '결말', '던', '그래도', '감동', '필요없', '는', '"', '00000082', '시작', ',', '전설', '오래된', '00920758', '모든', '00335020', '물의', '아버지', '말', '명작', '00001858', '걸작', '<', '>', '!', '지만', '정말', '재밌었', '멋진', '여', '굿', '자유', '향한', '끝없', '희망', '만들어', '낸', '현실', '과', '이상', '넘어선', '참된', '교육', '보', '여준', '우리', '에겐', '여전히', '된', '....', '내', '인생', '중', '하나', '00230755', '너무', '대작', '로서', '가치', '충분하다', '외계인', '나오는', 

In [101]:
fasttext.wv['아련한']

array([ 0.12585352,  0.34550503,  0.04384864,  0.17455468, -0.01557248,
       -0.07441817, -0.03710788,  0.05919386, -0.04417224, -0.09324055,
        0.10331282, -0.0379455 ,  0.1745775 ,  0.02637103, -0.24209093,
        0.3043294 , -0.24953641, -0.15145832,  0.08339852, -0.12621178,
       -0.07485531,  0.08249438, -0.02188313, -0.14289838, -0.09575988,
       -0.07071347, -0.26042876,  0.07581172, -0.243551  , -0.25375116,
        0.09194282,  0.16156293, -0.23060764,  0.06984485,  0.14801015,
       -0.02383949, -0.00984   ,  0.21952564, -0.13915667, -0.00723665,
        0.12654544, -0.11792067, -0.06778286,  0.14571372, -0.12022155,
        0.02673644, -0.11484886,  0.0644029 ,  0.04958085, -0.24964184,
       -0.03250542,  0.16685937,  0.04194087, -0.12531203,  0.09710729,
       -0.12636158, -0.1368438 ,  0.12336853,  0.04852116,  0.17926422,
       -0.10425676,  0.02023916,  0.16385818, -0.08664377,  0.04647343,
       -0.02923903,  0.21015225, -0.1854284 ,  0.14024723, -0.18

In [94]:
embedding[word2idx['아련한']] == fasttext.wv['아련한']

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [130]:
np.array([0,1,2])*6

array([ 0,  6, 12])

In [68]:
vocab_words = list(fasttext.wv.vocab.keys())
word2idx = {word: idx for idx, word in enumerate(vocab_words)}
word2idx['<UNK>'] = len(vocab_words)
word2idx['<PAD>'] = len(vocab_words) + 1

idx2word = {idx: word for idx, word in enumerate(vocab_words)}
idx2word[len(vocab_words)] = '<UNK>'
idx2word[len(vocab_words) + 1] = '<PAD>'
print("word2idx", word2idx['쓰레기'], word2idx['<PAD>'])
print("idx2word", idx2word[word2idx['쓰레기']], idx2word[word2idx['<PAD>']])
print("vocab_words", vocab_words[0])

word2idx 1325 1802
idx2word 쓰레기 <PAD>
vocab_words 아련한


In [71]:
len(vocab_words)

1801

In [72]:
word_vectors = []
vocab_num = len(vocab_words)
for i in range(20000):
    if i < vocab_num:
        word = idx2word[i]
        if word in ['<UNK>', '<PAD>']:
            vector = np.zeros(300)
        else:
            vector = fasttext.wv[word]
        word_vectors.append(vector)
    else:
        word_vectors.append(np.zeros(300))
embedding = np.stack(word_vectors)

In [74]:
embedding.shape

(20000, 300)

In [112]:
from torch import nn

In [136]:
means = []
stds = []
for line in embedding:
    if max(line)!=0:
        means.append(np.mean(line))
        stds.append(np.std(line))

In [145]:
a = np.array([1,2,3,4,5,1,2])

In [146]:
np.where(a==1)

(array([0, 5]),)

In [142]:
fasttext.wv['아련한']*6

array([ 1.0044891 ,  1.7309743 , -0.01600995,  1.0514331 ,  0.03373226,
       -0.37927872, -0.26643   , -0.09503628, -0.28660262, -0.6055443 ,
        0.5811312 , -0.3850143 ,  1.3206023 ,  0.19087511, -1.096188  ,
        1.6964366 , -1.4548951 , -1.2905979 ,  0.6513135 , -0.44771844,
       -0.2764277 ,  0.6859629 ,  0.10906826, -0.7805574 , -0.80850863,
       -0.23475257, -1.8096282 ,  0.44272158, -1.1341342 , -1.3649487 ,
        0.49819452,  1.0854046 , -1.4835625 ,  0.77287614,  0.6910709 ,
       -0.21059093, -0.59639055,  1.3376572 , -1.1407024 ,  0.11652195,
        0.8086895 , -0.864062  , -0.6897711 ,  0.6163567 , -0.59884995,
        0.4637614 , -0.7936934 , -0.07427627,  0.12777053, -1.3972409 ,
       -0.29765537,  1.1526603 ,  0.26375785, -0.8688575 ,  0.53574455,
       -1.0195352 , -0.82933134,  0.8874973 ,  0.33949086,  0.96740115,
       -0.65425617,  0.08780906,  0.8868481 , -0.46400845,  0.43618947,
       -0.2619563 ,  1.1840444 , -1.0485255 ,  0.9090885 , -0.94

In [141]:
np.random.normal(size=300)

300

In [143]:
from torch.utils.data import sampler

In [149]:
import soynlp

ModuleNotFoundError: No module named 'soynlp'